
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 22;
  public static final int STRING_LITERAL = 41;
  public static final int LBRACKET = 13;
  public static final int CHAR_LITERAL = 40;
  public static final int LPAREN = 15;
  public static final int SEMI = 11;
  public static final int CONTINUE = 9;
  public static final int INT = 33;
  public static final int FOR = 6;
  public static final int MINUS = 20;
  public static final int RPAREN = 16;
  public static final int NOT = 31;
  public static final int AND = 29;
  public static final int CALLOUT = 32;
  public static final int OR = 30;
  public static final int COMMA = 12;
  public static final int CLASS = 2;
  public static final int GREATHER_THAN_EQUALS = 26;
  public static final int PLUS = 19;
  public static final int ASSIGN = 10;
  public static final int IF = 4;
  public static final int ID = 37;
  public static final int EOF = 0;
  public static final int BOOLEAN = 34;
  public static final int RETURN = 7;
  public static final int RBRACKET = 14;
  public static final int TRUE = 35;
  public static final int PROGRAM = 38;
  public static final int error = 1;
  public static final int GREATHER_THAN = 24;
  public static final int BREAK = 8;
  public static final int VOID = 3;
  public static final int TIMES = 21;
  public static final int LBRACE = 17;
  public static final int ELSE = 5;
  public static final int NOT_EQUALS = 28;
  public static final int RBRACE = 18;
  public static final int EQUALS_EQUALS = 27;
  public static final int FALSE = 36;
  public static final int LESS_THAN = 23;
  public static final int LESS_THAN_EQUALS = 25;
  public static final int INT_LITERAL = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "VOID",
  "IF",
  "ELSE",
  "FOR",
  "RETURN",
  "BREAK",
  "CONTINUE",
  "ASSIGN",
  "SEMI",
  "COMMA",
  "LBRACKET",
  "RBRACKET",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LESS_THAN",
  "GREATHER_THAN",
  "LESS_THAN_EQUALS",
  "GREATHER_THAN_EQUALS",
  "EQUALS_EQUALS",
  "NOT_EQUALS",
  "AND",
  "OR",
  "NOT",
  "CALLOUT",
  "INT",
  "BOOLEAN",
  "TRUE",
  "FALSE",
  "ID",
  "PROGRAM",
  "INT_LITERAL",
  "CHAR_LITERAL",
  "STRING_LITERAL"
  };
}

